default_prompt_endpoint: "127.0.0.1"
load_balancing: "round_robin"
timeout_ms: 5000

overrides:
  # confidence threshold for prompt target intent matching
  prompt_target_intent_matching_threshold: 0.6

llm_providers:

  - name: open-ai-gpt-4
    api_key: $OPEN_AI_API_KEY
    model: gpt-4
    default: true

prompt_targets:

  - type: function_resolver
    name: weather_forecast
    description: This function resolver provides weather forecast information for a given city.
    parameters:
      - name: city
        required: true
        description: The city for which the weather forecast is requested.
      - name: days
        description: The number of days for which the weather forecast is requested.
      - name: units
        description: The units in which the weather forecast is requested.
    endpoint:
      cluster: api_server
      path: /weather
    system_prompt: |
      You are a helpful weather forecaster. Use weater data that is provided to you. Please following following guidelines when responding to user queries:
      - Use farenheight for temperature
      - Use miles per hour for wind speed
  - type: function_resolver
    name: insurance_claim_details
    description: This function resolver provides insurance claim details for a given policy number.
    parameters:
      - name: policy_number
        required: true
        description: The policy number for which the insurance claim details are requested.
    endpoint:
      cluster: api_server
      path: /insurance_claim_details
    system_prompt: |
      You are a helpful insurance claim details provider. Use insurance claim data that is provided to you. Please following following guidelines when responding to user queries:
      - Use policy number to retrieve insurance claim details
