default_prompt_endpoint: "127.0.0.1"
load_balancing: "round_robin"
timeout_ms: 5000

model_host_preferences:
  - name: jailbreak
    # if host is not specified, it will be run on the gpu if its available otherwise it will run on cpu
    host_preference:
      - gpu
      - cpu
    # revision: "refs/pr13"
  - name: toxic
    host_preference:
      - cpu
  - name: arch-fc
    host_preference: ec2

# should not be here
embedding_provider:
  name: "bge-large-en-v1.5"
  model: "BAAI/bge-large-en-v1.5"

llm_providers:

  - name: open-ai-gpt-4
    api_key: $OPEN_AI_API_KEY
    model: gpt-4
    default: true

prompt_guards:
   input_guards:
      jailbreak:
        on_exception_message: Looks like you are curious about my jailbreak detection abilities.
      toxicity:
        on_exception_message: Looks like you are curious about my toxicity detection abilities.

prompt_targets:

  - type: function_resolver
    name: weather_forecast
    description: This function resolver provides weather forecast information for a given city.
    parameters:
      - name: city
        required: true
        description: The city for which the weather forecast is requested.
      - name: days
        description: The number of days for which the weather forecast is requested.
      - name: units
        description: The units in which the weather forecast is requested.
    endpoint:
      cluster: weatherhost
      path: /weather
    system_prompt: |
      You are a helpful weather forecaster. Use weater data that is provided to you. Please following following guidelines when responding to user queries:
      - Use farenheight for temperature
      - Use miles per hour for wind speed
