repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: check-yaml
        exclude: arch/envoy.template*
      - id: end-of-file-fixer
      - id: trailing-whitespace
  - repo: local
    hooks:
      - id: cargo-fmt
        name: cargo-fmt
        language: system
        types: [file, rust]
        entry: bash -c "cd arch && cargo fmt -p intelligent-prompt-gateway -- --check"
      - id: cargo-clippy
        name: cargo-clippy
        language: system
        types: [file, rust]
        entry: bash -c "cd arch && cargo clippy -p intelligent-prompt-gateway --all"
      - id: cargo-test
        name: cargo-test
        language: system
        types: [file, rust]
        # --lib is to only test the library, since when integration tests are made,
        # they will be in a seperate tests directory
        entry: bash -c "cd arch && cargo test -p intelligent-prompt-gateway --lib"
  - repo: https://github.com/psf/black
    rev: 23.1.0
    hooks:
      - id: black
        language_version: python3
