repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: check-yaml
        exclude: arch/envoy.template*
      - id: end-of-file-fixer
      - id: trailing-whitespace
  - repo: local
    hooks:

      - id: cargo-fmt
        name: cargo-fmt
        language: system
        types: [file, rust]
        entry: bash -c "cd crates/llm_gateway && cargo fmt -- --check"

      - id: cargo-clippy
        name: cargo-clippy
        language: system
        types: [file, rust]
        entry: bash -c "cd crates/llm_gateway && cargo clippy --all"

      - id: cargo-test
        name: cargo-test
        language: system
        types: [file, rust]
        # --lib is to only test the library, since when integration tests are made,
        # they will be in a seperate tests directory
        entry: bash -c "cd crates/llm_gateway && cargo test --lib"
      - id: python-tests
        name: Run Python Tests with pytest
        language: system
        entry: bash -c "cd model_server && pytest --maxfail=5 --disable-warnings"
        types: [python]


  - repo: https://github.com/psf/black
    rev: 23.1.0
    hooks:
      - id: black
        language_version: python3
