services:
  api_server:
    build:
      context: .
    environment:
      - SLACK_BOT_TOKEN=${SLACK_BOT_TOKEN:-None}
      - OPENAI_API_KEY=${OPENAI_API_KEY:?error}
      - CHAT_COMPLETION_ENDPOINT=http://host.docker.internal:10000/v1
    volumes:
      - ./arch_config.yaml:/app/arch_config.yaml
      - ../shared/chatbot_ui/common.py:/app/common.py
    ports:
      - "18080:80"
    healthcheck:
        test: ["CMD", "curl" ,"http://localhost:80/healthz"]
        interval: 5s
        retries: 20
