version: v0.1
listener:
  address: 127.0.0.1
  port: 8080 #If you configure port 443, you'll need to update the listener with tls_certificates
  message_format: huggingface

system_prompt: |
  You are an insurance assistant that just offers guidance related to car, boat, rental and home insurnace only. Please be pricese and summarize based on the context provided.

llm_providers:
  - name: OpenAI
    provider: openai
    access_key: $OPENAI_API_KEY
    model: gpt-4o
    default: true

# Arch creates a round-robin load balancing between different endpoints, managed via the cluster subsystem.
endpoints:
  app_server:
    # value could be ip address or a hostname with port
    # this could also be a list of endpoints for load balancing
    # for example endpoint: [ ip1:port, ip2:port ]
    endpoint: host.docker.internal:18083
    # max time to wait for a connection to be established
    connect_timeout: 0.05s

prompt_targets:
  - name: policy_qa
    http_method: POST
    endpoint:
      name: app_server
      path: /policy/qa
    description: Handle general Q/A related to insurance.
    default: true

  - name: get_policy_coverage
    description: Retrieve the coverage details for a given policy type (car, boat, house, motorcycle).
    http_method: POST
    endpoint:
      name: app_server
      path: /policy/coverage
    parameters:
    - name: policy_type
      type: str
      description: The type of policy, option - car, boat, house, motorcycle.
      default: car
      required: true

  - name: initiate_policy
    http_method: POST
    endpoint:
      name: app_server
      path: /policy/initiate
    description: Start a policy coverage for car, boat, motorcycle or house.
    parameters:
    - name: policy_type
      type: str
      description: The type of policy, option - car, boat, house, motorcycle.
      default: car
      required: true
    - name: deductible
      type: float
      description: the deductible amount set of the policy
      required: true

  - name: update_claim
    http_method: POST
    endpoint:
      name: app_server
      path: /policy/claim
    description: Update the notes on the claim
    parameters:
    - name: claim_id
      type: str
      description: the claim number
      required: true
    - name: notes
      type: str
      description: notes about the cliam number for your adjustor to see
      required: false

  - name: update_deductible
    http_method: POST
    endpoint:
      name: app_server
      path: /policy/deductible
    description: Update the deductible amount for a specific policy coverage.
    parameters:
    - name: policy_id
      type: str
      description: The id of the policy
      required: true
    - name: deductible
      type: float
      description: the deductible amount set of the policy
      required: true

ratelimits:
  - model: gpt-4
    selector:
      key: selector-key
      value: selector-value
    limit:
      tokens: 1
      unit: minute
