services:
  envoy:
    image: envoyproxy/envoy:v1.30-latest
    hostname: envoy
    ports:
      - "10000:10000"
      - "19901:9901"
    volumes:
      - ./envoy.yaml:/etc/envoy/envoy.yaml
      - ./target/wasm32-wasi/release:/etc/envoy/proxy-wasm-plugins
    networks:
      - envoymesh
    depends_on:
      embeddingserver:
        condition: service_healthy

  embeddingserver:
    build:
      context: ../embedding-server
      dockerfile: Dockerfile
    ports:
      - "18080:80"
    healthcheck:
        test: ["CMD", "curl" ,"http://localhost:80"]
        interval: 5s
        retries: 20
    networks:
      - envoymesh

  vector-db:
    image: qdrant/qdrant
    hostname: vector-db
    ports:
      - 16333:6333
      - 16334:6334
    volumes:
      - ./vector_db:/qdrant/storage
    networks:
      - envoymesh

networks:
  envoymesh: {}
