$schema: "http://json-schema.org/draft-07/schema#"
type: object
properties:
  version:
    type: string
  listener:
    type: object
    properties:
      address:
        type: string
      port:
        type: integer
      message_format:
        type: string
      connect_timeout:
        type: string
    additionalProperties: false
    required:
      - address
      - port
  endpoints:
    type: object
    patternProperties:
      "^.*$":
        type: object
        properties:
          endpoint:
            type: string
          connect_timeout:
            type: string
        additionalProperties: false
        required:
          - endpoint
  llm_providers:
    type: array
    items:
      type: object
      properties:
        name:
          type: string
        provider:
          type: string
        access_key:
          type: string
        model:
          type: string
        default:
          type: boolean
      additionalProperties: false
      required:
        - name
        - provider
        - access_key
        - model
  overrides:
    type: object
    properties:
      prompt_target_intent_matching_threshold:
        type: number
  system_prompt:
    type: string
  prompt_targets:
    type: array
    items:
      type: object
      properties:
        name:
          type: string
        default:
          type: boolean
        description:
          type: string
        auto_llm_dispatch_on_response:
          type: boolean
        parameters:
          type: array
          items:
            type: object
            properties:
              name:
                type: string
              additionalProperties: false
              required:
                type: boolean
              default:
                type: string
              description:
                type: string
              type:
                type: string
            additionalProperties: false
            required:
              - name
              - description
              - type
        endpoint:
          type: object
          properties:
            name:
              type: string
            path:
              type: string
          additionalProperties: false
          required:
            - name
            - path
        system_prompt:
          type: string
      additionalProperties: false
      required:
        - name
        - description
  ratelimits:
    type: array
    items:
      type: object
      properties:
        model:
          type: string
        selector:
          type: object
          properties:
            key:
              type: string
            value:
              type: string
          additionalProperties: false
          required:
            - key
            - value
        limit:
          type: object
          properties:
            tokens:
              type: integer
            unit:
              type: string
          additionalProperties: false
          required:
            - tokens
            - unit
      additionalProperties: false
      required:
        - model
        - selector
        - limit
  tracing:
    type: object
    properties:
      random_sampling:
        type: integer
      trace_arch_internal:
        type: boolean
      additionalProperties: false
  mode:
    type: string
    enum:
      - llm
      - prompt
additionalProperties: false
required:
  - version
  - listener
  - llm_providers
